services:

  authenticationservice:
    image: "ghcr.io/nager/nager.authenticationservice:latest"
    environment:
      CONNECTIONSTRINGS__DEFAULT: Server=database;Database=AuthenticationService;User Id=sa;Password=yourStrong(!)Password;MultipleActiveResultSets=true;TrustServerCertificate=true;
      ASPNETCORE_ENVIRONMENT: Development
      AUTHENTICATION__TOKENS__ISSUER: ChangeMe
      AUTHENTICATION__TOKENS__AUDIENCE: ChangeMe
      AUTHENTICATION__TOKENS__SIGNINGKEY: The.SigningKey.ForUserData.PLEASE.CHANGE.ME.REQUIRE.A.128.BIT.KEY
    ports:
      - 80:8080
    depends_on:
      - database

  database:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: yourStrong(!)Password
