name: Docker Image CI

on:
  push:
    paths:
    - 'src/**'
    - '.github/workflows/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'src/**'
    - '.github/workflows/**'
    branches: [ main ]

jobs:
  build-spa:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src/Frontend

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Clean slate
      run: npm ci
      working-directory: ${{env.working-directory}}
    - name: Install quasar
      run: npm install -g @quasar/cli
      working-directory: ${{env.working-directory}}
    - name: Build
      run: quasar build
      working-directory: ${{env.working-directory}}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: spa
        # Directory containing files to upload
        path: ${{env.working-directory}}/dist/spa/
        # Days before delete
        retention-days: 1

  build-api:
    
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/Backend/Nager.AuthenticationService.WebApi

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ${{env.working-directory}}
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
#      working-directory: ${{env.working-directory}}
    - name: Publish
      run: dotnet publish --no-restore --configuration Release --output publish
      working-directory: ${{env.working-directory}}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: api
        # Directory containing files to upload
        path: ${{env.working-directory}}/publish/
        # Days before delete
        retention-days: 1

  build-docker:

    needs: [build-api, build-spa]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: api
        path: publish
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: spa
        path: publish/wwwroot
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push the Docker image
      run: |
        docker build ./src --file src/Dockerfile --tag ghcr.io/nager/nager.authenticationservice:latest
        docker push ghcr.io/nager/nager.authenticationservice:latest
